USE [DynamicsAxProd]
GO

/****** Object:  View [dbo].[vw_BOM2]    Script Date: 09/13/2013 11:32:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[vw_BOM2] AS
SELECT 
	BOM.BOMID, BOM.RECID AS [BOM Rec ID], BOM.bomqty as [Qty per par], BOM.ITEMID AS [Item ID], Child.BOMID AS [Child BOM ID], Child.Name AS [Child Name],  
	INVENTTABLE.ITEMNAME as [Mfg Item Name], INVENTTABLE.MFGITEMNUMBER as [Mfg Item Number], INVENTTABLE.ITEMMFG as [Item Mfg],
	INVENTTABLE.RECID AS [Mfg Rec ID],  
	M.price as [Cost], ISNULL([dbo].[GetQOHForItemIDs](INVENTTABLE.ITEMID, '00', INVENTTABLE.DATAAREAID),0) as 'WH0'
FROM BOM 
	INNER JOIN BOMVERSION ON BOMVERSION.BOMID = BOM.BOMID and BOMVERSION.DATAAREAID = 'us' and BOMVERSION.APPROVED = 1 
	INNER JOIN INVENTTABLE ON INVENTTABLE.ITEMID = BOM.ITEMID AND INVENTTABLE.DATAAREAID = 'us' 
		LEFT OUTER JOIN InventTableModule AS M ON M.ITEMID = INVENTTABLE.ITEMID and INVENTTABLE.DATAAREAID = M.DATAAREAID AND MODULETYPE = 0 
	LEFT OUTER JOIN BOMVERSION Child ON INVENTTABLE.ITEMID = Child.ITEMID and Child.DATAAREAID = 'us' and Child.ACTIVE = 1 and Child.APPROVED = 1 
WHERE BOM.DATAAREAID = 'us' AND BOMVERSION.BOMID = BOM.BOMID   
GO


